/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsWebhooksRouteImport } from './routes/settings/webhooks'
import { Route as SettingsProviderKeysRouteImport } from './routes/settings/provider-keys'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsAlertsRouteImport } from './routes/settings/alerts'
import { Route as ProxyPlaygroundRouteImport } from './routes/proxy/playground'
import { Route as ApplicationsIdRouteImport } from './routes/applications/$id'
import { Route as AnalyticsEventsRouteImport } from './routes/analytics/events'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminBillingIndexRouteImport } from './routes/admin/billing/index'
import { Route as AdminBillingProductsRouteImport } from './routes/admin/billing/products'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWebhooksRoute = SettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProviderKeysRoute = SettingsProviderKeysRouteImport.update({
  id: '/settings/provider-keys',
  path: '/settings/provider-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAlertsRoute = SettingsAlertsRouteImport.update({
  id: '/settings/alerts',
  path: '/settings/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyPlaygroundRoute = ProxyPlaygroundRouteImport.update({
  id: '/proxy/playground',
  path: '/proxy/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsEventsRoute = AnalyticsEventsRouteImport.update({
  id: '/analytics/events',
  path: '/analytics/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingIndexRoute = AdminBillingIndexRouteImport.update({
  id: '/admin/billing/',
  path: '/admin/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingProductsRoute = AdminBillingProductsRouteImport.update({
  id: '/admin/billing/products',
  path: '/admin/billing/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/analytics/events': typeof AnalyticsEventsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/proxy/playground': typeof ProxyPlaygroundRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/provider-keys': typeof SettingsProviderKeysRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/billing/products': typeof AdminBillingProductsRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/analytics/events': typeof AnalyticsEventsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/proxy/playground': typeof ProxyPlaygroundRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/provider-keys': typeof SettingsProviderKeysRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/admin': typeof AdminIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/applications': typeof ApplicationsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/billing/products': typeof AdminBillingProductsRoute
  '/admin/billing': typeof AdminBillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/analytics/events': typeof AnalyticsEventsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/proxy/playground': typeof ProxyPlaygroundRoute
  '/settings/alerts': typeof SettingsAlertsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/provider-keys': typeof SettingsProviderKeysRoute
  '/settings/webhooks': typeof SettingsWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/admin/billing/products': typeof AdminBillingProductsRoute
  '/admin/billing/': typeof AdminBillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/integration'
    | '/login'
    | '/overview'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/pricing'
    | '/analytics/events'
    | '/applications/$id'
    | '/proxy/playground'
    | '/settings/alerts'
    | '/settings/billing'
    | '/settings/provider-keys'
    | '/settings/webhooks'
    | '/admin/'
    | '/analytics/'
    | '/applications/'
    | '/settings/'
    | '/admin/billing/products'
    | '/admin/billing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/integration'
    | '/login'
    | '/overview'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/pricing'
    | '/analytics/events'
    | '/applications/$id'
    | '/proxy/playground'
    | '/settings/alerts'
    | '/settings/billing'
    | '/settings/provider-keys'
    | '/settings/webhooks'
    | '/admin'
    | '/analytics'
    | '/applications'
    | '/settings'
    | '/admin/billing/products'
    | '/admin/billing'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/integration'
    | '/login'
    | '/overview'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/audit-logs'
    | '/admin/customers'
    | '/admin/pricing'
    | '/analytics/events'
    | '/applications/$id'
    | '/proxy/playground'
    | '/settings/alerts'
    | '/settings/billing'
    | '/settings/provider-keys'
    | '/settings/webhooks'
    | '/admin/'
    | '/analytics/'
    | '/applications/'
    | '/settings/'
    | '/admin/billing/products'
    | '/admin/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IntegrationRoute: typeof IntegrationRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AnalyticsEventsRoute: typeof AnalyticsEventsRoute
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  ProxyPlaygroundRoute: typeof ProxyPlaygroundRoute
  SettingsAlertsRoute: typeof SettingsAlertsRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsProviderKeysRoute: typeof SettingsProviderKeysRoute
  SettingsWebhooksRoute: typeof SettingsWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AdminBillingProductsRoute: typeof AdminBillingProductsRoute
  AdminBillingIndexRoute: typeof AdminBillingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/webhooks': {
      id: '/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof SettingsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/provider-keys': {
      id: '/settings/provider-keys'
      path: '/settings/provider-keys'
      fullPath: '/settings/provider-keys'
      preLoaderRoute: typeof SettingsProviderKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/alerts': {
      id: '/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/settings/alerts'
      preLoaderRoute: typeof SettingsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy/playground': {
      id: '/proxy/playground'
      path: '/proxy/playground'
      fullPath: '/proxy/playground'
      preLoaderRoute: typeof ProxyPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/events': {
      id: '/analytics/events'
      path: '/analytics/events'
      fullPath: '/analytics/events'
      preLoaderRoute: typeof AnalyticsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing/': {
      id: '/admin/billing/'
      path: '/admin/billing'
      fullPath: '/admin/billing/'
      preLoaderRoute: typeof AdminBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing/products': {
      id: '/admin/billing/products'
      path: '/admin/billing/products'
      fullPath: '/admin/billing/products'
      preLoaderRoute: typeof AdminBillingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IntegrationRoute: IntegrationRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AnalyticsEventsRoute: AnalyticsEventsRoute,
  ApplicationsIdRoute: ApplicationsIdRoute,
  ProxyPlaygroundRoute: ProxyPlaygroundRoute,
  SettingsAlertsRoute: SettingsAlertsRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsProviderKeysRoute: SettingsProviderKeysRoute,
  SettingsWebhooksRoute: SettingsWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AdminBillingProductsRoute: AdminBillingProductsRoute,
  AdminBillingIndexRoute: AdminBillingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
